### ISSUE TITLE
Cannot overcome "This transcript is still being processed for display" condition

### ISSUE THREAD

**Issue by McFateM** [digitalutsc/islandora_solution_pack_oralhistories#143]
I need to pull the latest code and try this again, but lately I've been having problems resolving the condition indicated in the title.  

So, for some time now when we use the provided editor to modify one of our TRANSCRIPTs it frequently saves an "empty" cue (looks like <cue/>) at the head of the TRANSCRIPT XML data.  This doesn't seem to cause any real problems, but when an administrator opens the object they typically see this... 

```
Notice: Undefined offset: 7 in islandora_oralhistories_transcripts_ui_transcript() (line 175 of /var/www/html/sites/all/modules/islandora/islandora_solution_pack_oralhistories/includes/utilities.inc). =>

    ... (Array, 15 elements)
    Krumo version 0.2.1a | http://krumo.sourceforge.net
    [Click to expand. Double-click to show path.] Called from /var/www/html/sites/all/modules/islandora/islandora_solution_pack_oralhistories/includes/utilities.inc, line 175  

Notice: Undefined offset: 7 in islandora_oralhistories_transcripts_ui_transcript() (line 176 of /var/www/html/sites/all/modules/islandora/islandora_solution_pack_oralhistories/includes/utilities.inc). =>

    ... (Array, 15 elements)
    Krumo version 0.2.1a | http://krumo.sourceforge.net
    [Click to expand. Double-click to show path.] Called from /var/www/html/sites/all/modules/islandora/islandora_solution_pack_oralhistories/includes/utilities.inc, line 176  

Notice: Undefined offset: 7 in islandora_oralhistories_transcripts_ui_transcript() (line 181 of /var/www/html/sites/all/modules/islandora/islandora_solution_pack_oralhistories/includes/utilities.inc). =>

    ... (Array, 15 elements)
    Krumo version 0.2.1a | http://krumo.sourceforge.net
    [Click to expand. Double-click to show path.] Called from /var/www/html/sites/all/modules/islandora/islandora_solution_pack_oralhistories/includes/utilities.inc, line 181  

Notice: Undefined offset: 7 in islandora_oralhistories_transcripts_ui_transcript() (line 186 of /var/www/html/sites/all/modules/islandora/islandora_solution_pack_oralhistories/includes/utilities.inc). => 
```

Presumably this is because the number of cues is inflated by the presence of the empty cue at the top of the XML.

Quite some time ago I created a Drush command as part of a utility suite that I've written, and with it I'm able to easily remove the empty <cue/>.  However, doing so leaves the object in a state where the title message is produced.  

In the past I've been able to re-index the object in Solr, and then regenerate derivatives in order to get the object back to a viewable state, but today that is no longer working.

I'm going to pull the latest 7.x code and test this again, and I'll follow-up here with results ASAP.

**Comment by MarcusBarnes** [comment]
@McFateM This is probably the same issue as was reported in https://github.com/Islandora-Labs/islandora_solution_pack_oralhistories/issues/134.   This has been addressed and is part of the [7.x-1.12 release of the solution pack](https://github.com/Islandora-Labs/islandora_solution_pack_oralhistories/releases/tag/7.x-1.12).

**Comment by McFateM** [comment]
@MarcusBarnes   The new code does seem to have addressed the empty cue issue.  I opened an object that had that problem, regenerated derivatives, and the empty cue / index errors are gone.  However, the "This transcript is still being processed for display" condition still exists, and I can't seem to find a way to get past it.

Any suggestions what it takes to clear that condition?   

I'm rebuilding a new local instance of Islandora (using ISLE) and hope to do some debugging this afternoon to see if I can determine what the root cause is.

**Comment by MarcusBarnes** [comment]
@McFateM I'd suggest trying to reindexing the object in Solr.   This can be accomplished using Gsearch and possibly also by editing and saving the MODS XML datastream.    Also double check that any caches have been cleared (both Drupal and browser, and if you're using something like Varnish, by-passing that cache as well).

**Comment by McFateM** [comment]
@MarcusBarnes Yes, re-indexing in Solr / FGS used to do the trick, but I've confirmed that it isn't anymore.  I'm running tests in a incognito window (no browser cache) and have cleared the Drupal cache too.  Even regeneration of the derivatives doesn't seem to clear it.  I also tried deleting the object from FGS/Solr and rebuilding it.  Still no good.

**Comment by MarcusBarnes** [comment]
The next step would be to explore the code around https://github.com/Islandora-Labs/islandora_solution_pack_oralhistories/blob/7.x/includes/utilities.inc#L95 and see why the expression in https://github.com/Islandora-Labs/islandora_solution_pack_oralhistories/blob/7.x/includes/utilities.inc#L91 is not evaluating to true.

**Comment by SummittDweller** [comment]
Just dropping a note here to let all know that I've come back around to looking at this again...finally.  I'm going to pull the latest 7.x-1.12 code, create a fork to do some debugging in, and cross my fingers.  I found the mentioned location in utilities.inc so I'll start there.  Wish me luck.
